### PR TITLE
Fix conflicts updating resources

### LINKED ISSUE #937: conflicts when patching a resource
### What happened?

Occasionally, resources are tried to be updated but this is not possible because they have been modified by another entity (CAPI). This can be avoided by using MergeFrom in the patch to calculate the diff.

### Involved Areas

_No response_

### What did you expect to happen?

No conflicts updating resources.

### Steps to reproduce

-

### k0smotron version

 1.4.0

### k0s version

any

### Anything else we need to know?

releted to https://github.com/k0smotron/k0smotron/issues/921

### PR DESCRIPTION
**Pull request by apedriza**
fix #937 

Change patch followed strategy to using https://pkg.go.dev/sigs.k8s.io/cluster-api@v1.8.5/util/patch. This packages uses `client.MergeFrom` option to patch the resource using the diff between updated one and the original. This way we prevent conflicts if other controller are updating the resource concurrently. By adopting this new patch strategy, some bugs have appeared when updating resources. For example, not taking into account the previous status when filing the resource. This was not a problem because only the subresource `.status` was updated but at runtime the resource could have duplicate values (see diff comments).

New approach it is only change in those resources which can potentially face a conflict when they are updated by k0smotron and CAPI.

### CODE REVIEW

File: api/controlplane/v1beta1/k0s_types.go [hunk 1]
```diff
@@ -127,15 +127,55 @@ type K0sControlPlaneList struct {
...
+	UnavailableReplicas int32 `json:"unavailableReplicas"`
+
+	// readyReplicas is the total number of fully running and ready control plane machines.
+	// +optional
+	ReadyReplicas int32 `json:"readyReplicas"`
+
+	// updatedReplicas is the total number of non-terminated machines targeted by this control plane
+	// that have the desired template spec.
+	// +optional
+	UpdatedReplicas int32 `json:"updatedReplicas"`
```
Comment (apedriza) [inline api/controlplane/v1beta1/k0s_types.go:178]: required mark them as `optional` for a correct patch

File: internal/controller/controlplane/k0smotron_controlplane_controller.go [hunk 2]
```diff
@@ -221,10 +232,7 @@ func (c *K0smotronController) waitExternalAddress(ctx context.Context, cluster *
 			log.Info("Updated infrastructure cluster", "host", host, "port", port)
 			cluster.Spec.ControlPlaneEndpoint.Host = host
 			cluster.Spec.ControlPlaneEndpoint.Port = int32(port)
-			if err := c.Client.Update(ctx, cluster); err != nil {
-				log.Error(err, "Failed to update Cluster endpoint")
-				return false, err
-			}
```
Comment (apedriza) [inline internal/controller/controlplane/k0smotron_controlplane_controller.go:227]: `cluster` is updated in the _defer_ func in `Reconcile` loop. Removing resources updates within the recocile loop as much as possible.

File: internal/controller/controlplane/k0smotron_controlplane_controller.go [hunk 3]
```diff
@@ -295,35 +304,27 @@ func (c *K0smotronController) reconcile(ctx context.Context, cluster *clusterv1.
...
-		if kcp.Spec.ExternalAddress == "" {
-			kcp.Spec.ExternalAddress = foundCluster.Spec.ExternalAddress
-		}
-		if !reflect.DeepEqual(foundCluster.Spec, kcp.Spec) {
-			err := c.Client.Patch(ctx, &kcluster, client.Apply, &client.PatchOptions{
-				FieldManager: "k0smotron",
-			})
 
-			return ctrl.Result{}, false, err
-		}
```
Comment (apedriza) [inline internal/controller/controlplane/k0smotron_controlplane_controller.go:313]: I think is not needed because `kcluster` has no changes since is retrieved couple lines above.

File: internal/controller/k0smotron.io/k0smotroncluster_configmap.go [hunk 4]
```diff
@@ -60,7 +60,7 @@ func (r *ClusterReconciler) generateConfig(kmc *km.Cluster, sans []string) (v1.C
 		case "k0s.k0sproject.io/v1beta1":
 			existingSANs, found, err := unstructured.NestedStringSlice(unstructuredConfig, "spec", "api", "sans")
 			if err == nil && found {
-				sans = append(sans, existingSANs...)
+				sans = kcontrollerutil.AddToExistingSans(existingSANs, sans)
```
Comment (apedriza) [inline internal/controller/k0smotron.io/k0smotroncluster_configmap.go:63]: avoiding duplicates values here too.

File: internal/controller/k0smotron.io/k0smotroncluster_configmap.go [hunk 5]
```diff
@@ -247,7 +251,7 @@ func getV1Beta1Spec(kmc *km.Cluster, sans []string) map[string]interface{} {
 			"type": "etcd",
 			"etcd": map[string]interface{}{
 				"externalCluster": map[string]interface{}{
-					"endpoints":      []string{fmt.Sprintf("https://%s:2379", kmc.GetEtcdServiceName())},
+					"endpoints":      []interface{}{fmt.Sprintf("https://%s:2379", kmc.GetEtcdServiceName())},
```
Comment (apedriza) [inline internal/controller/k0smotron.io/k0smotroncluster_configmap.go:254]: `Unstructured.DeepCopy` neither support `int` not `[]string` so converting them to supported types. More info here: https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/converter.go#L636. This is hit by the new _patch_ package introduced.

File: internal/controller/k0smotron.io/k0smotroncluster_controller.go [hunk 6]
```diff
@@ -179,64 +192,52 @@ func (r *ClusterReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
...
+		if !isAPIServerEtcdClientCertRef {
+			logger.Info("Reconciling etcd certs")
+			err := r.ensureEtcdCertificates(ctx, kmc)
+			if err != nil {
+				return ctrl.Result{Requeue: true, RequeueAfter: time.Minute}, fmt.Errorf("error generating etcd certificates: %w", err)
+			}
+			kmc.Spec.CertificateRefs = append(kmc.Spec.CertificateRefs, km.CertificateRef{
+				Type: string(secret.APIServerEtcdClient),
+				Name: secret.Name(kmc.Name, secret.APIServerEtcdClient),
+			})
```
Comment (apedriza) [inline internal/controller/k0smotron.io/k0smotroncluster_controller.go:211]: this is to avoid values duplicated. In the same loop certificates were propagated to statufulset correctly and after that `.spec` was not updated (which I think i should be updated) only `.status` was updated

File: internal/controller/k0smotron.io/k0smotroncluster_service.go [hunk 7]
```diff
@@ -178,9 +178,6 @@ func (r *ClusterReconciler) reconcileServices(ctx context.Context, kmc km.Cluste
 			return err
 		}
 		kmc.Spec.ExternalAddress = util.FindNodeAddress(nodes)
-		if err := r.Client.Update(ctx, &kmc); err != nil {
-			return err
-		}
```
Comment (apedriza) [inline internal/controller/k0smotron.io/k0smotroncluster_service.go:183]: updated in main _defer_

**Review by makhov — APPROVED** [review]
Just a small comment

File: internal/controller/controlplane/k0smotron_controlplane_controller.go [hunk 8]
```diff
@@ -137,8 +149,12 @@ func (c *K0smotronController) Reconcile(ctx context.Context, req ctrl.Request) (
 		log.Error(err, "Reconciliation failed")
 		return res, err
 	}
+	if !res.IsZero() {
```
[the remark this answers is not in the document]
Comment (apedriza) [reply internal/controller/controlplane/k0smotron_controlplane_controller.go:154]: Great, added a comment about requeue when k0smotron cluster just been created. https://github.com/k0smotron/k0smotron/compare/28b437b059ba652eba3be9cf1f0bb0030d53e3b5..f308dbca07f8f4cedd819515b82a89d1d73bdf7d
